Adding jacoco coverage report
paypal/mocca pull request #25
Opened 2021-08-07 03:48 UTC by abhijith-prabhakar

2021-08-07 15:10 UTC, fabiocarvalho777 requested changes
Please add a hashtag followed by issue number at the end of all commit and PR names.

2021-08-07 15:11 UTC, fabiocarvalho777 requested changes

2021-08-07 15:11 UTC, fabiocarvalho777 commented on build.gradle
> +    test {
Just double checking, did you test to see if the report is generated properly per module?

Also, did you check if an aggregate report is generated at the root? For Codacy to work we will need that (or at least that is how it used to be).

2021-08-07 19:52 UTC, AmandeepSingh97 reviewed
Are we pushing changes directly to master? I read in contribution doc that we have to put them to develop branch.

2021-08-09 20:41 UTC, fabiocarvalho777 commented
> Are we pushing changes directly to master? I read in contribution doc that we have to put them to develop branch.

You are totally right Aman!! Thanks for catching that!!

@abhijith-prabhakar please, can you close this PR and create a new one out of develop branch to develop branch? Thanks.

2021-09-19 19:04 UTC, closed without merging