Fix timeout support #41
paypal/mocca pull request #47
Opened 2021-09-27 20:02 UTC by crankydillo

See the issue for more info, but basically the code I'm replacing
assumed that:

1. Connect/read timeout was always done with client creation.
2. Our impl (technically feign) couldn't successfully set those per
   request.

This work addresses the above and 3 issues:

1. How a client can specify how the timeouts are specified.
2. How the builder chain can honor the above in a nice way (i.e if you
   a client says it doesn't support request timeouts then those aren't
   exposed via the build chain.
3. How to test without repetition.

So, it was just interesting to try and solve this.  Now, I don't think
this code is super-complicated, but I can understand distaste for this.
I primarily did it just out of interest:)  I think you could make a
decent argument that we just bring back the timeout methods to all
builder chains and in the jaxrs2+client (we could still add a builder
option), we'd just log that these are ignored.  That's unfortunate, but
if this is the only case where we need to ignore request-level timeouts,
then I can understand not wanting this code.

2021-10-06 11:32 UTC, crankydillo commented
@fabiocarvalho777 I pushed some more javadoc.  As we discussed, the main user impact here is to the builder.  At a certain point, you supply a client (or use `defaultClient()`) where the client implementations leverage marker interfaces to determine whether or not the builder should expose timeouts or not.  Most do expose timeouts.  Currently, only JAX-RS does not.

This is not feature complete.  I need to do something similar for async, finish up testing, and adjust user doc.  However, the main idea is there, and I thought this might be controversial, so I didn't want to do any needless work.  This was supposed to be opened as a draft, but I guess didn't do that the 2nd go around.

2021-10-18 20:05 UTC, fabiocarvalho777 requested changes

2021-10-18 20:05 UTC, fabiocarvalho777 commented on mocca-jaxrs2/src/main/java/com/paypal/mocca/client/MoccaJaxrsClient.java
> +            "However, those are ignored.  They should be established in the supplied javax.ws.rs.Client.");
@crankydillo out of curiosity, why do you always add two spaces after a period?

2021-10-18 20:05 UTC, fabiocarvalho777 commented on mocca-jaxrs2/src/main/java/com/paypal/mocca/client/MoccaJaxrsClient.java
> +        log.info("Mocca implementation _may_ attempt to set read timeout and connect timeout per request.  " +
I would prefer to not have this log message, since there is no attempt to change timeouts right here. I believe a message like this might confuse sers, it would be better to just log a message like this when an attempt to change a timeout actually happens.

2021-10-18 20:05 UTC, fabiocarvalho777 commented on mocca-jaxrs2/build.gradle
> +                       lib.activation
Which line of code, or situation, required the inclusion of this dependency?

2021-10-18 20:05 UTC, fabiocarvalho777 commented on mocca-client/src/main/java/com/paypal/mocca/client/MoccaClient.java
> +            public class WithRequestTimeouts extends Base {
Should this be package private, like `WithoutRequestTimeouts`?

2021-10-18 20:05 UTC, fabiocarvalho777 commented on mocca-client/src/main/java/com/paypal/mocca/client/MoccaClient.java
> +                WithRequestTimeouts options(
I am confused. Is this method supposed to be exposed to end-users via Mocca API? If so, shouldn't it be public?

2021-10-18 20:05 UTC, fabiocarvalho777 commented on mocca-client/src/main/java/com/paypal/mocca/client/MoccaClient.java
> +                    final Duration connectTimeout,
What if end user only wants to provide `connectTimeout`?

2021-10-18 20:05 UTC, fabiocarvalho777 commented on mocca-client/src/main/java/com/paypal/mocca/client/MoccaClient.java
> +            public class WithRequestTimeouts extends Base {
I am confused with the name of this class. As I review this PR, I have always to come back here to try to understand what it means. Let me see if I can explain what I mean:\

Correct me if I am wrong but, regardless of this type, clients will always be "with request timeouts". The difference is whether they are supposed to be configured using Mocca API or the client native API.

If I understood this right, clients of this type will only let users set timeouts using Mocca API. Is that right?

2021-11-01 15:22 UTC, crankydillo commented on mocca-jaxrs2/src/main/java/com/paypal/mocca/client/MoccaJaxrsClient.java
> +            "However, those are ignored.  They should be established in the supplied javax.ws.rs.Client.");
Standard (American) English rules:)

2021-11-13 12:50 UTC, crankydillo commented on mocca-client/src/main/java/com/paypal/mocca/client/MoccaClient.java
> +            public class WithRequestTimeouts extends Base {
Fabio and I spoke about this, but for posterity...

`WithRequestTimeouts` and `WithoutRequestTimouts` are just builder paths.  The former exposes Mocca builder-based timeout establishment.  I'm not a huge fan of the names either, but it's not really anticipated that clients 'see' these types very much.  I assume they'll just chain the builder methods.

Clients will not always send you down the `WithRequestTimeouts` path.  The client passed in will either support Mocca builder-based timeouts or not (most currently do).  The ones that do implement an interface that sends you down the `WithRequestTimeouts` path where they can set the socket and connect timeout with Mocca builder methods.  The ones that don't (jaxrs) send you down the `WithoutRequestTimeouts` path where they can't.  For the latter, we assume that native client functionality is used to set the timeouts.  The reason for this trickery is that our underlying client facade will try to set default timeout values so any `MoccaHttpClient` we feed in must be able to ignore that.

2022-01-05 17:25 UTC, crankydillo commented on mocca-jaxrs2/src/main/java/com/paypal/mocca/client/MoccaJaxrsClient.java
> +        log.info("Mocca implementation _may_ attempt to set read timeout and connect timeout per request.  " +
That means you will always get that message for every request.  Of course, people can disable that, but they'll need to go do that explicitly.  I guess I could set it to trace.  Anyhow, let me just remove this altogether now.  It's not crystal clear this is needed.

2022-02-05 15:06 UTC, crankydillo commented on mocca-jaxrs2/build.gradle
> +                       lib.activation
Honestly, I don't recall.  I thought the build basically told me to, but I just removed it and am still getting green builds with `./gradlew clean test`.  I will remove `lib.activation`.

2022-02-05 15:06 UTC, crankydillo commented on mocca-client/src/main/java/com/paypal/mocca/client/MoccaClient.java
> +                    final Duration connectTimeout,
They are out of luck?  :)

2022-02-05 15:10 UTC, crankydillo commented
@fabiocarvalho777 This is my proposed fix.  It does include a few other fixes, primarily related to the `C` in feign's `AsyncClient<C>`.

I did not update the end user doc.  I am hoping you will be willing to do that after we decide if this is what we want to do.

I will fix any reasonable CI failures.

2022-02-09 16:51 UTC, fabiocarvalho777 approved these changes

2022-02-16 21:05 UTC, abhijith-prabhakar approved these changes

2022-02-17 14:32 UTC, merged